apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  namespace: tpb-dev
  name: jenkins
rules:
  - apiGroups: [""]
    #
    # at the HTTP level, the name of the resource for accessing Secret
    # objects is "secrets"
    resources: ["deployment", "secrets", "pods", "services", "namespaces"]
    verbs: ["create", "get", "update", "patch", "list", "delete"]
  # - apiGroups: ["apps"]
  #   resources: ["deployments", "namespaces"]
  #   verbs: ["create", "get", "update", "patch", "list", "delete"]


